---
- name: IaaS Provisioning
  hosts: localhost
  gather_facts: false
  collections:
    - nutanix.ncp
  vars:
      nutanix_host: #<host_ip>
      nutanix_username: #<user>
      nutanix_password: #<password>
      validate_certs: false
      
  module_defaults:

    group/nutanix.ncp.ntnx:
      nutanix_host: '{{ nutanix_host }}'
      nutanix_username: '{{ nutanix_username }}'
      nutanix_password: '{{ nutanix_password }}'
      validate_certs: '{{ validate_certs }}'
  tasks:
    - include_role:
        name: external_subnet
    - include_role:
        name: vpc
    - include_role:
        name: overlay_subnet
    - include_role:
        name: vm
    - include_role:
        name: fip
