---
- name: IaaS Provisioning
  hosts: localhost
  gather_facts: false
  module_defaults:
    group/nutanix.ncp.ntnx:
      nutanix_host: <pc_ip>
      nutanix_username: <user>
      nutanix_password: <pass>
      validate_certs: false
  tasks:
    - name: Include vars file
      ansible.builtin.include_vars:
        file: vars.yml
    - name: Include  external_subnet role
      ansible.builtin.include_role:
        name: external_subnet
    - name: Include vpc role
      ansible.builtin.include_role:
        name: vpc
    - name: Include static_route role
      ansible.builtin.include_role:
        name: static_route
    - name: Include overlay_subnet role
      ansible.builtin.include_role:
        name: overlay_subnet
    - name: Include vm role
      ansible.builtin.include_role:
        name: vm
    - name: Include fip role
      ansible.builtin.include_role:
        name: fip
