---
- name: Policy based routing - NACLs
  hosts: localhost
  gather_facts: false
  collections:
    - nutanix.ncp
  vars:
      nutanix_host: 10.44.76.88
      nutanix_username: admin
      nutanix_password: Nutanix.123
      validate_certs: false
  module_defaults:

    group/nutanix.ncp.ntnx:
      nutanix_host: '{{ nutanix_host }}'
      nutanix_username: '{{ nutanix_username }}'
      nutanix_password: '{{ nutanix_password }}'
      validate_certs: '{{ validate_certs }}'
  ignore_errors: true
  tasks:
    - include_role:
        name: pbr
