---
- name: Policy based routing - NACLs
  hosts: localhost
  gather_facts: false
  module_defaults:
    group/nutanix.ncp.ntnx:
      nutanix_host: <pc_ip>
      nutanix_username: <user>
      nutanix_password: <pass>
      validate_certs: false
  tasks:
    - name: Include pbr role
      ansible.builtin.include_role:
        name: pbr_delete
