---
  - name: Create {{ item.name }} external subnet
    ntnx_subnets:
      state: present
      name: "{{ item.name }}"
      external_subnet:
        vlan_id: "{{ item.vlan_id }}"
        cluster:
          name: "{{ cluster.name }}"
        enable_nat: "{{ item.eNat }}"
        ipam:
          network_ip: "{{ item.ip }}"
          network_prefix: "{{ item.prefix }}"
          gateway_ip: "{{ item.gip }}"
          ip_pools:
            - start_ip: "{{ item.sip }}"
              end_ip: "{{ item.eip }}"
    register: external_network
  - debug:
      msg: 
        - "name: Ext_Nat" 
        - "uuid: {{ external_network.subnet_uuid }}"