namespace: "nutanix"
name: "ncp"
version: "2.4.0"
readme: "README.md"
authors:
  - "Abhishek Chaudhary (@abhimutant)"
  - "Pradeepsingh Bhati (@bhati-pradeep)"
  - "Prem Karat (@premkarat)"
  - "Gevorg Khachatryan (@Gevorg-Khachatryan-97)"
  - "Alaa Bishtawi (@alaa-bish)"
  - "Abhinav Bansal (@abhinavbansal29)"
  - "George Ghawali (@george-ghawali)"
description: Nutanix Ansible Collection
license_file: "LICENSE"
tags: [nutanix, prism, ahv, cloud, infrastructure]
repository: https://github.com/nutanix/nutanix.ansible
documentation: https://github.com/nutanix/nutanix.ansible/blob/main/README.md
homepage: https://github.com/nutanix/nutanix.ansible/
issues: https://github.com/nutanix/nutanix.ansible/issues
build_ignore:
  # https://docs.ansible.com/ansible/devel/dev_guide/developing_collections_distributing.html#ignoring-files-and-folders
  - .gitignore
  - changelogs/.plugin-cache.yaml
  - .github
  - .vscode
