---
- name: Inputs for vm task
  ansible.builtin.include_tasks: vm.yml
  with_items:
    - name: Prod-Wordpress-App
      desc: Prod-Wordpress-App
      is_connected: true
      subnet_name: "{{ Prod_SubnetA.name }}"
      image_name: wordpress-appserver
      private_ip: ""
    - name: Prod-Wordpress-DB
      desc: Prod-Wordpress-DB
      is_connected: true
      subnet_name: "{{ Prod_SubnetB.name }}"
      image_name: wordpress-db
      private_ip: 10.1.2.5
    - name: Dev-Wordpress-App
      desc: Dev-Wordpress-App
      is_connected: true
      subnet_name: "{{ Dev_SubnetA.name }}"
      image_name: wordpress-appserver
      private_ip: ""
    - name: Dev-Wordpress-DB
      desc: Dev-Wordpress-DB
      is_connected: true
      subnet_name: "{{ Dev_SubnetB.name }}"
      image_name: wordpress-db
      private_ip: 10.1.2.5
