---
- name: Define vpc_uuids variable
  ansible.builtin.set_fact:
    vpc_uuids: []
- name: Inputs vpcs task
  ansible.builtin.include_tasks: vpc.yml
  with_items:
    - { name: "{{ vpc_names[0] }}", subnet_name: "{{ external_subnet.name }}" }
    - { name: "{{ vpc_names[1] }}", subnet_name: "{{ external_subnet.name }}" }
