---
- name: Test Inventory Plugin
  hosts: all
  gather_facts: false
  vars_files:
    - nutanix.yml
  tasks:
    - name: Assert the number of VMs in case of fetch_all_vms is false # noqa run-once[task]
      ansible.builtin.assert:
        that:
          - ansible_play_hosts | length <= data.length
        fail_msg: "No hosts found in inventory!"
        success_msg: "Found {{ ansible_play_hosts | length }} hosts in inventory!"
      run_once: true
      when: not fetch_all_vms

    - name: Assert the number of VMs in case of fetch_all_vms is true # noqa run-once[task]
      ansible.builtin.assert:
        that:
          - ansible_play_hosts | length >= 0
        fail_msg: "No hosts found in inventory!"
        success_msg: "Found {{ ansible_play_hosts | length }} hosts in inventory!"
      run_once: true
      when: fetch_all_vms

    - name: Assert that host vars are defined like ansible_host, ansible_fqdn, uuid, name, cluster
      ansible.builtin.assert:
        that:
          - hostvars[inventory_hostname].ansible_host is defined
          - hostvars[inventory_hostname].ansible_fqdn is defined
          - hostvars[inventory_hostname].uuid is defined
          - hostvars[inventory_hostname].name is defined
          - hostvars[inventory_hostname].cluster is defined
        fail_msg: "Host vars not found for {{ inventory_hostname }}"
        success_msg: "Host vars found for {{ inventory_hostname }}"

    - name: Assert host groups # noqa run-once[task]
      ansible.builtin.assert:
        that:
          - hostvars[inventory_hostname].groups is defined
          - hostvars[inventory_hostname].groups | length >= 3
          - hostvars[inventory_hostname].groups.all is defined
          - hostvars[inventory_hostname].groups.all | length >= 0
          - hostvars[inventory_hostname].groups.group_1 | length +
            hostvars[inventory_hostname].groups.group_2 | length +
            hostvars[inventory_hostname].groups.group_3 | length ==
            hostvars[inventory_hostname].groups.all | length
          - hostvars[inventory_hostname].groups.group_1 | intersect(hostvars[inventory_hostname].groups.group_2) | length == 0
          - hostvars[inventory_hostname].groups.group_1 | intersect(hostvars[inventory_hostname].groups.group_3) | length == 0
          - hostvars[inventory_hostname].groups.group_2 | intersect(hostvars[inventory_hostname].groups.group_3) | length == 0
        fail_msg: "Hosts are not in the expected groups"
        success_msg: "Hosts are in the expected groups"
      run_once: true
      when:
        - hostvars[inventory_hostname].groups.group_1 is defined
        - hostvars[inventory_hostname].groups.group_2 is defined
        - hostvars[inventory_hostname].groups.group_3 is defined

    - name: Set host IP and FQDN
      ansible.builtin.set_fact:
        host_ip: "{{ hostvars[inventory_hostname].ansible_host | regex_replace('\\.', '_') }}"
        host_fqdn: "{{ hostvars[inventory_hostname].ansible_fqdn | regex_replace('\\.', '_') }}"

    - name: Assert host keyed groups
      ansible.builtin.assert:
        that:
          - ('host_' ~ host_ip) in hostvars[inventory_hostname].groups.keys()
        fail_msg: "Host keyed groups not found for {{ inventory_hostname }}"
        success_msg: "Host keyed groups found for {{ inventory_hostname }}"
      when:
        - hostvars[inventory_hostname].ansible_host is defined
        - hostvars[inventory_hostname].ansible_host is not none
        - hostvars[inventory_hostname].ansible_host | length > 0

    - name: Assert FQDN keyed groups
      ansible.builtin.assert:
        that:
          - ('fqdn_' ~ host_fqdn) in hostvars[inventory_hostname].groups.keys()
        fail_msg: "FQDN keyed groups not found for {{ inventory_hostname }}"
        success_msg: "FQDN keyed groups found for {{ inventory_hostname }}"
      when:
        - hostvars[inventory_hostname].ansible_fqdn is defined
        - hostvars[inventory_hostname].ansible_fqdn is not none
        - hostvars[inventory_hostname].ansible_fqdn | length > 0

    - name: Assert cluster group
      ansible.builtin.assert:
        that:
          - hostvars[inventory_hostname].cluster is defined
          - hostvars[inventory_hostname].cluster | length > 0
          - hostvars[inventory_hostname].cluster in hostvars[inventory_hostname].groups.keys()
        fail_msg: "Cluster group not found for {{ inventory_hostname }}"
        success_msg: "Cluster group found for {{ inventory_hostname }}"
      when:
        - hostvars[inventory_hostname].cluster is defined
        - hostvars[inventory_hostname].cluster is not none
        - hostvars[inventory_hostname].cluster | length > 0
