---
- name: Delete PBR "{{ item.pbr_uuid }}"
  nutanix.ncp.nutanix.ncp.ntnx_pbrs:
    state: absent
    pbr_uuid: "{{ item.pbr_uuid }}"
  register: pbr_delete_result
- name: Print pbr uuid
  ansible.builtin.debug:
    msg:
      - "uuid: {{ pbr_delete_result.pbr_uuid }}"
