---
- name: Delete PBR "{{ item.pbr_uuid }}"
  nutanix.ncp.nutanix.ncp.ntnx_pbrs:
    state: absent
    pbr_uuid: "{{ item.pbr_uuid }}"
  register: pbr
- name: Print pbr uuid
  ansible.builtin.debug:
    msg:
      - "uuid: {{ pbr.pbr_uuid }}"
