---
# Summary:
# This playbook will do:
# 1. Install NGT in VM with reboot preference set to IMMEDIATE
# 2. Fetch NGT config after installing NGT in VM with reboot preference set to IMMEDIATE
# 3. Update NGT in VM by disabling it and setting capabilities to VSS_SNAPSHOT
# 4. Upgrade NGT in VM
# 5. Insert ISO into CD ROM in VM
# 6. Uninstall NGT in VM

- name: VM ngt playbook
  hosts: localhost
  gather_facts: false
  module_defaults:
    group/nutanix.ncp.ntnx:
      nutanix_host: <pc_ip>
      nutanix_username: <user>
      nutanix_password: <pass>
      validate_certs: false
  tasks:
    - name: Setting Variables
      ansible.builtin.set_fact:
        vm_uuid: "323e4567-e89b-12d3-a456-426614174001"
        vm_username: "username"
        vm_password: "password"

    - name: Install NGT in VM with reboot preference set to IMMEDIATE
      nutanix.ncp.ntnx_vms_ngt_v2:
        state: present
        ext_id: "{{ vm_uuid }}"
        capabilities:
          - VSS_SNAPSHOT
        credential:
          username: "{{ vm_username }}"
          password: "{{ vm_password }}"
        reboot_preference:
          schedule_type: IMMEDIATE
      register: result
      ignore_errors: true

    - name: Fetch NGT config after installing NGT in VM with reboot preference set to IMMEDIATE
      nutanix.ncp.ntnx_vms_ngt_info_v2:
        ext_id: "{{ vm_uuid }}"
      register: result
      ignore_errors: true

    - name: Update NGT in VM by disabling it and setting capabilities to VSS_SNAPSHOT
      nutanix.ncp.ntnx_vms_ngt_update_v2:
        state: present
        ext_id: "{{ vm_uuid }}"
        is_enabled: false
        capabilities:
          - VSS_SNAPSHOT
      register: result
      ignore_errors: true

    - name: Upgrade NGT in VM
      nutanix.ncp.ntnx_vms_ngt_upgrade_v2:
        state: present
        ext_id: "{{ vm_uuid }}"
        reboot_preference:
          schedule_type: "SKIP"
      register: result
      ignore_errors: true

    - name: Insert ISO for config only after NGT upgrade
      nutanix.ncp.ntnx_vms_ngt_insert_iso_v2:
        state: present
        ext_id: "{{ vm_uuid }}"
        capabilities:
          - SELF_SERVICE_RESTORE
        is_config_only: true
      register: result
      ignore_errors: true

    - name: Uninstall NGT in VM
      nutanix.ncp.ntnx_vms_ngt_v2:
        state: absent
        ext_id: "{{ vm_uuid }}"
      register: result
      ignore_errors: true
