---
# Summary:
# This playbook will do:
# 1. Create a VM with minimum requirements
# 2. Create a VM with full requirements
# 3. Create a VM with different disks, using ubuntu image , with cdrom
# 4. Create a VM with multiple serial port, and categories
# 5. Create a VM with nics,cloud_init script
# 6. Create a VM with windows unattend xml file

- name: VM crud playbook
  hosts: localhost
  gather_facts: false
  module_defaults:
    group/nutanix.ncp.ntnx:
      nutanix_host: <pc_ip>
      nutanix_username: <user>
      nutanix_password: <pass>
      validate_certs: false
  tasks:
    - name: Setting Variables
      ansible.builtin.set_fact:
        vm_name: "VM name"
        cluster:
          uuid: "0006501f-7367-e963-543f-52540043fbd9"
        vm_uuid: "1944c6b3-f81f-4641-627f-c5ef7887bf01"
        disk_image:
          image_ext_ids:
            - "7c4d4fa3-085c-43ae-97d5-1fdb5c92eaee"
        storage_container:
          uuid: "1a2c7de1-7c12-4d04-a79c-703a2f8bff50"
        network:
          dhcp:
            uuid: "ac70d801-0e5d-450f-bb76-adf3234e0530"
        category_ext_id_1: "66f4d0aa-4e77-5261-94c6-4dc19a857049"
        category_ext_id_2: "594bb16c-3498-5706-bd9d-301dea6a6bcb"
        xml_file_content: "{{ lookup('ansible.builtin.file', 'unattend_xml_content.xml') }}"
        cloud_init_user_data: |
          #cloud-config
          disable_root: false
          ssh_pwauth:   true

    - name: Create VM with minimum requirements
      nutanix.ncp.ntnx_vms_v2:
        name: "{{ vm_name }}"
        description: ansible test
        cluster:
          ext_id: "{{ cluster.uuid }}"
      register: result
      ignore_errors: true

    - name: Create VM with full requirements
      nutanix.ncp.ntnx_vms_v2:
        name: "{{ vm_name }}"
        description: ansible test
        cluster:
          ext_id: "{{ cluster.uuid }}"
        num_sockets: 1
        num_cores_per_socket: 1
        num_threads_per_core: 1
        num_numa_nodes: 1
        memory_size_bytes: 4294967296
        is_vcpu_hard_pinning_enabled: false
        is_cpu_passthrough_enabled: false
        is_memory_overcommit_enabled: false
        is_gpu_console_enabled: false
        is_vga_console_enabled: false
        machine_type: PC
        hardware_clock_timezone: UTC
        enabled_cpu_features:
          - HARDWARE_VIRTUALIZATION
        is_branding_enabled: false
        is_agent_vm: false
        apc_config:
          is_apc_enabled: false
        vtpm_config:
          is_vtpm_enabled: false
      register: result
      ignore_errors: true

    - name: Create vm with different disks, using ubuntu image , with cdrom
      nutanix.ncp.ntnx_vms_v2:
        name: "{{ vm_name }}"
        description: ansible test
        cluster:
          ext_id: "{{ cluster.uuid }}"
        cd_roms:
          - disk_address:
              bus_type: IDE
            backing_info:
              data_source:
                reference:
                  image_reference:
                    image_ext_id: "{{ disk_image.image_ext_ids[0] }}"
        disks:
          - backing_info:
              vm_disk:
                disk_size_bytes: 26843545600
                storage_container:
                  ext_id: "{{ storage_container.uuid }}"
            disk_address:
              bus_type: SCSI
              index: 2
          - backing_info:
              vm_disk:
                disk_size_bytes: 26843545600
                data_source:
                  reference:
                    image_reference:
                      image_ext_id: "{{ disk_image.image_ext_ids[0] }}"
            disk_address:
              bus_type: SCSI
              index: 3
      register: result
      ignore_errors: true

    - name: Create vm with multiple serial port, and categories
      nutanix.ncp.ntnx_vms_v2:
        name: "{{ vm_name }}"
        description: ansible test
        cluster:
          ext_id: "{{ cluster.uuid }}"
        categories:
          - ext_id: "{{ category_ext_id_1 }}"
          - ext_id: "{{ category_ext_id_2 }}"
        serial_ports:
          - is_connected: true
            index: 0
          - is_connected: true
            index: 3
      register: result
      ignore_errors: true

    - name: Create vm with nics,cloud_init script
      nutanix.ncp.ntnx_vms_v2:
        name: "{{ vm_name }}"
        description: ansible test
        cluster:
          ext_id: "{{ cluster.uuid }}"
        nics:
          - network_info:
              subnet:
                ext_id: "{{ network.dhcp.uuid }}"
        disks:
          - backing_info:
              vm_disk:
                disk_size_bytes: 26843545600
                storage_container:
                  ext_id: "{{ storage_container.uuid }}"
            disk_address:
              bus_type: SCSI
              index: 2
          - backing_info:
              vm_disk:
                disk_size_bytes: 26843545600
                data_source:
                  reference:
                    image_reference:
                      image_ext_id: "{{ disk_image.image_ext_ids[0] }}"
            disk_address:
              bus_type: SCSI
              index: 3
        guest_customization:
          config:
            cloudinit:
              datasource_type: CONFIG_DRIVE_V2
              cloud_init_script:
                user_data:
                  value: "{{ cloud_init_user_data | b64encode }}"
      register: result
      ignore_errors: true

    - name: Create vm with windows unattend xml file
      nutanix.ncp.ntnx_vms_v2:
        name: "{{ vm_name }}"
        description: ansible test
        cluster:
          ext_id: "{{ cluster.uuid }}"
        guest_customization:
          config:
            sysprep:
              install_type: "FRESH"
              sysprep_script:
                unattendxml:
                  value: "{{ xml_file_content | b64encode }}"
      register: result
      ignore_errors: true

    - name: Create VM with vtpm enabled
      nutanix.ncp.ntnx_vms_v2:
        name: "{{ vm_name }}"
        description: ansible test
        cluster:
          ext_id: "{{ cluster.uuid }}"
        machine_type: Q35
        boot_config:
          uefi_boot:
            is_secure_boot_enabled: true
        vtpm_config:
          is_vtpm_enabled: true
      register: result
      ignore_errors: true

    - name: Update VM
      nutanix.ncp.ntnx_vms_v2:
        state: present
        ext_id: "{{ vm_uuid }}"
        name: "{{ vm_name }}"
        description: "vm description"
        cluster:
          ext_id: "{{ cluster.uuid }}"
        num_sockets: 1
        num_cores_per_socket: 1
        num_threads_per_core: 1
        num_numa_nodes: 1
        memory_size_bytes: 4294967296
        is_vcpu_hard_pinning_enabled: false
        is_cpu_passthrough_enabled: false
        is_memory_overcommit_enabled: false
        is_gpu_console_enabled: false
        is_vga_console_enabled: false
        machine_type: PC
        hardware_clock_timezone: UTC
        enabled_cpu_features:
          - HARDWARE_VIRTUALIZATION
        is_branding_enabled: false
        is_agent_vm: false
        apc_config:
          is_apc_enabled: false
        vtpm_config:
          is_vtpm_enabled: false
      register: result
      ignore_errors: true

    - name: List all VMs
      nutanix.ncp.ntnx_vms_info_v2:
      register: result
      ignore_errors: true

    - name: List all VMs with limit
      nutanix.ncp.ntnx_vms_info_v2:
        limit: 2
      register: result
      ignore_errors: true

    - name: Get vm using filter name
      nutanix.ncp.ntnx_vms_info_v2:
        filter: name eq '{{ vm_name }}'
      register: result
      ignore_errors: true

    - name: Fetch VM
      nutanix.ncp.ntnx_vms_info_v2:
        ext_id: "{{ vm_uuid }}"
      register: result
      ignore_errors: true

    - name: Delete VM
      nutanix.ncp.ntnx_vms_v2:
        state: absent
        ext_id: "{{ vm_uuid }}"
      register: result
      ignore_errors: true
