---
# Summary:
# This playbook will do:
# 1. Update guest script (cloud-init)
# 2. Update guest script (Windows sysprep)

- name: VM guest guest customization playbook
  hosts: localhost
  gather_facts: false
  module_defaults:
    group/nutanix.ncp.ntnx:
      # nutanix_host: <pc_ip>
      # nutanix_username: <user>
      # nutanix_password: <pass>
      # validate_certs: false
  tasks:
    - name: Setting Variables
      ansible.builtin.set_fact:
        vm_uuid: "e07a5d6f-df91-4966-7689-af181ed5f34c"
        unattend_xml_content: "{{ lookup('ansible.builtin.file', 'unattend_xml_content.xml') }}"
        cloud_init_user_data: |
          #cloud-config
          disable_root: false
          ssh_pwauth:   true

    - name: Update guest script
      nutanix.ncp.ntnx_vms_stage_guest_customization_v2:
        ext_id: "{{ vm_uuid }}"
        config:
          cloudinit:
            datasource_type: CONFIG_DRIVE_V2
            cloud_init_script:
              user_data:
                value: "{{ cloud_init_user_data | b64encode }}"
      register: result

    - name: Update guest script (Windows sysprep)
      nutanix.ncp.ntnx_vms_stage_guest_customization_v2:
        ext_id: "{{ vm_uuid }}"
        config:
          sysprep:
            install_type: "FRESH"
            sysprep_script:
              unattendxml:
                value: "{{ unattend_xml_content | b64encode }}"
      register: result
