---
# Summary:
# This playbook will do:
# 1. Create VM
# 2. Update VM
# 3. Fetch VM
# 4. Delete VM

- name: VM crud playbook
  hosts: localhost
  gather_facts: false
  module_defaults:
    group/nutanix.ncp.ntnx:
      # nutanix_host: <pc_ip>
      # nutanix_username: <user>
      # nutanix_password: <pass>
      validate_certs: false
  tasks:
    - name: Create VM
      nutanix.ncp.ntnx_vms_v2:
        enable_debug_logging: true
        state: present
        name: "test-vm"
        cluster:
          ext_id: "10064237-e79d-e7fc-5a41-5254000e6dd1"
      register: result
      ignore_errors: true

    - name: Set VM UUID
      set_fact:
        vm_uuid: "{{ result.response.ext_id }}"

    - name: Update VM
      nutanix.ncp.ntnx_vms_v2:
        enable_debug_logging: true
        state: present
        ext_id: "{{ vm_uuid }}"
        name: "test-vm_updated"
        cluster:
          ext_id: "00064237-e79d-e7fc-5a41-5254000e6dd1"

    - name: Fetch VM
      nutanix.ncp.ntnx_vms_info_v2:
        # enable_debug_logging: true
        filter: name eq 'test-vm_updated' and cluster/extId eq '00064237-e79d-e7fc-5a41-5254000e6dd1'
        limit: 1
      register: result_updated
      ignore_errors: true

    - name: Show VM result
      debug:
        var: result_updated
      when: not result_updated.failed

    - name: Delete VM
      nutanix.ncp.ntnx_vms_v2:
        enable_debug_logging: true
        state: absent
        ext_id: "{{ vm_uuid }}"
