---
- name: Create k8s cluster
  hosts: localhost
  gather_facts: false
  module_defaults:
    group/nutanix.ncp.ntnx:
      nutanix_host: <pc_ip>
      nutanix_username: <user>
      nutanix_password: <pass>
      validate_certs: false

  tasks:
    - name: Set vars
      ansible.builtin.set_fact:
        cluster:
          name: <cluster_name>
          uuid: <cluster_uuid>
        node_subnet:
          name: <subnet_name>
          uuid: <subnet_uuid>
        storage_class:
          name: <storage_class_name>
        storage_container:
          name: <storage_container_name>
        cni:
          node_cidr_mask_size: 24
          service_ipv4_cidr: 172.19.0.0/16
          pod_ipv4_cidr: 172.20.0.0/16
        karbon_name: test-module21
        k8s_version: 1.19.8-0
        host_os: ntnx-1.0
        nutanix_cluster_password: <pass>
        nutanix_cluster_username: <username>
        control_plane_virtual_ip: <control_plane_virtual_ip>

    #############################
    - name: Create  DEV cluster with Flannel network provider
      nutanix.ncp.ntnx_karbon_clusters:
        cluster:
          uuid: "{{ cluster.uuid }}"
        name: "{{ karbon_name }}"
        k8s_version: "{{ k8s_version }}"
        host_os: "{{ host_os }}"
        node_subnet:
          name: "{{ node_subnet.name }}"
        cluster_type: DEV
        cni:
          node_cidr_mask_size: "{{ cni.node_cidr_mask_size }}"
          service_ipv4_cidr: "{{ cni.service_ipv4_cidr }}"
          pod_ipv4_cidr: "{{ cni.pod_ipv4_cidr }}"
          network_provider: Flannel
        storage_class:
          nutanix_cluster_password: "{{ nutanix_cluster_password }}"
          nutanix_cluster_username: "{{ nutanix_cluster_username }}"
          default_storage_class: true
          name: "{{ storage_class.name }}"
          reclaim_policy: Delete
          storage_container: "{{ storage_container.name }}"
          file_system: ext4
          flash_mode: false
      register: result

    - name: Delete  dev cluster
      nutanix.ncp.ntnx_karbon_clusters:
        state: absent
        name: "{{ result.response.name }}"
      register: result

    - name: Create  DEV cluster with Calico network provider
      nutanix.ncp.ntnx_karbon_clusters:
        cluster:
          name: "{{ cluster.name }}"
        name: "{{ karbon_name }}"
        k8s_version: "{{ k8s_version }}"
        host_os: "{{ host_os }}"
        node_subnet:
          uuid: "{{ node_subnet.uuid }}"
        cni:
          node_cidr_mask_size: "{{ cni.node_cidr_mask_size }}"
          service_ipv4_cidr: "{{ cni.service_ipv4_cidr }}"
          pod_ipv4_cidr: "{{ cni.pod_ipv4_cidr }}"
          network_provider: Calico
        custom_node_configs:
          etcd:
            num_instances: 1
            cpu: 4
            memory_gb: 8
            disk_gb: 120
          masters:
            num_instances: 1
            cpu: 4
            memory_gb: 8
            disk_gb: 120
          workers:
            num_instances: 1
            cpu: 8
            memory_gb: 8
            disk_gb: 120
        storage_class:
          nutanix_cluster_password: "{{ nutanix_cluster_password }}"
          nutanix_cluster_username: "{{ nutanix_cluster_username }}"
          default_storage_class: true
          name: "{{ storage_class.name }}"
          reclaim_policy: Retain
          storage_container: "{{ storage_container.name }}"
          file_system: xfs
          flash_mode: true
      register: result

    - name: Create worker node pool with subnet uuid
      nutanix.ncp.ntnx_karbon_clusters_node_pools:
        node_subnet:
          uuid: <uuid>
        node_pool_name: "{{ karbon_name }}"
        cluster_name: "{{ cluster.name }}"
        pool_config:
          num_instances: 2
          cpu: 4
          memory_gb: 8
          disk_gb: 120
      register: result
      ignore_errors: true

    - name: Update pool by increasing cpu,memory_gb,num_instances and add labels
      nutanix.ncp.ntnx_karbon_clusters_node_pools:
        wait: true
        node_pool_name: "{{ karbon_name }}"
        cluster_name: "{{ cluster.name }}"
        pool_config:
          cpu: 6
          memory_gb: 10
          disk_gb: 150
          num_instances: 4
        add_labels:
          property1: test-property1
      register: result
      ignore_errors: true

    - name: Create prod cluster
      nutanix.ncp.ntnx_karbon_clusters:
        cluster:
          uuid: "{{ cluster.uuid }}"
        name: "{{ karbon_name }}"
        k8s_version: "{{ k8s_version }}"
        host_os: "{{ host_os }}"
        node_subnet:
          name: "{{ node_subnet.name }}"
        cluster_type: PROD
        cni:
          node_cidr_mask_size: "{{ cni.node_cidr_mask_size }}"
          service_ipv4_cidr: "{{ cni.service_ipv4_cidr }}"
          pod_ipv4_cidr: "{{ cni.pod_ipv4_cidr }}"
          network_provider: Flannel
        storage_class:
          nutanix_cluster_password: "{{ nutanix_cluster_password }}"
          nutanix_cluster_username: "{{ nutanix_cluster_username }}"
          default_storage_class: true
          name: "{{ storage_class.name }}"
          reclaim_policy: Delete
          storage_container: "{{ storage_container.name }}"
          file_system: ext4
          flash_mode: false
        control_plane_virtual_ip: "{{ control_plane_virtual_ip }}"
        custom_node_configs:
          etcd:
            num_instances: 1
            cpu: 4
            memory_gb: 8
            disk_gb: 240
          masters:
            num_instances: 1
            cpu: 4
            memory_gb: 8
            disk_gb: 240
          workers:
            num_instances: 1
            cpu: 8
            memory_gb: 8
            disk_gb: 240
      register: result
