---
- name: Get registries info
  hosts: localhost
  gather_facts: false
  module_defaults:
    group/nutanix.ncp.ntnx:
      nutanix_host: <pc_ip>
      nutanix_username: <user>
      nutanix_password: <pass>
      validate_certs: false

  tasks:
    - name: Test getting all registries
      nutanix.ncp.ntnx_karbon_registries_info:
      register: registries

    - name: Test getting particular register using name
      nutanix.ncp.ntnx_karbon_registries_info:
        registry_name: "{{ registries.response[1].name }}"
      register: result
