---
- name: API Keys Playbook
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Create a new API Key
      nutanix.ncp.ntnx_foundation_central_api_keys:
        nutanix_host: "{{ pc }}"
        nutanix_username: "{{ username }}"
        nutanix_password: "{{ password }}"
        validate_certs: false
        alias: test-alias
      register: output

    - name: Output of api_key
      ansible.builtin.debug:
        msg: "{{ output }}"
