---
- name: API Keys Info Playbook
  hosts: localhost
  gather_facts: false
  collections:
    - nutanix.ncp

  tasks:
    - name: API key response with alias
      nutanix.ncp.ntnx_foundation_central_api_keys:
        nutanix_host: "{{ pc }}"
        nutanix_username: "{{ username }}"
        nutanix_password: "{{ password }}"
        validate_certs: false
        alias: test
      register: output

    - name: API key response with key_uuid
      nutanix.ncp.ntnx_foundation_central_api_keys:
        nutanix_host: "{{ pc }}"
        nutanix_username: "{{ username }}"
        nutanix_password: "{{ password }}"
        validate_certs: false
        key_uuid: <key_uuid>
      register: output

    - name: Output of api_key
      ansible.builtin.debug:
        msg: "{{ output }}"
