---
- name: Prism playbook
  hosts: localhost
  gather_facts: false
  module_defaults:
    group/nutanix.ncp.ntnx:
      nutanix_host: <pc_ip>
      nutanix_username: <user>
      nutanix_password: <pass>
      validate_certs: false
  tasks:
    - name: Setting Variables
      ansible.builtin.set_fact:
        ip_pe_for_deploying_pc: "10.0.0.3"
        pc:
          name: "test"
          size: "SMALL"
          build_info:
            version: "pc.2024.3"
          external_networks:
            network_ext_id: "ba416f8d-00f2-499d-bc4c-19da8d104af9"
            default_gateway:
              ipv4: "10.33.232.1"
            subnet_mask:
              ipv4: "255.255.252.0"
            ip_ranges:
              begin:
                ipv4: "10.33.232.10"
              end:
                ipv4: "10.33.232.10"
          name_servers:
            ipv4: ["10.10.10.10", "10.10.10.11"]
          ntp_servers:
            fqdn: ["2.example.org", "3.example.org"]

    - name: Deploy PC
      nutanix.ncp.ntnx_pc_deploy_v2:
        nutanix_host: "{{ ip_pe_for_deploying_pc }}"
        config:
          name: "{{ pc.name }}_pc"
          size: "{{ pc.size }}"
          build_info:
            version: "{{ pc.build_info.version }}"
        network:
          external_networks:
            - default_gateway:
                ipv4:
                  value: "{{ pc.external_networks.default_gateway.ipv4 }}"
              subnet_mask:
                ipv4:
                  value: "{{ pc.external_networks.subnet_mask.ipv4 }}"
              ip_ranges:
                - begin:
                    ipv4:
                      value: "{{ pc.external_networks.ip_ranges.begin.ipv4 }}"
                  end:
                    ipv4:
                      value: "{{ pc.external_networks.ip_ranges.end.ipv4 }}"
              network_ext_id: "{{ pc.external_networks.network_ext_id }}"
          name_servers:
            - ipv4:
                value: "{{ pc.name_servers.ipv4[0] }}"
            - ipv4:
                value: "{{ pc.name_servers.ipv4[1] }}"
          ntp_servers:
            - fqdn:
                value: "{{ pc.ntp_servers.fqdn[0] }}"
            - fqdn:
                value: "{{ pc.ntp_servers.fqdn[1] }}"
      register: result
      ignore_errors: true
