---
- name: ACP_Info playbook
  hosts: localhost
  gather_facts: false
  collections:
    - nutanix.ncp
  module_defaults:
    group/nutanix.ncp.ntnx:
      nutanix_host: <pc_ip>
      nutanix_username: <user>
      nutanix_password: <pass>
      validate_certs: false

  tasks:
    - name: List ACPs using ascending, sorting and name filter
      nutanix.ncp.ntnx_floating_ips_info:
        filter:
          name: "{{ acp_name }}"
        kind: access_control_policy
        sort_order: ASCENDING
        sort_attribute: name
      register: result
      ignore_errors: true

    - name: List ACPs using length and offset
      nutanix.ncp.ntnx_floating_ips_info:
        length: 3
        offset: 0
      register: result
      ignore_errors: true
