---
- name: FIP_Info playbook
  hosts: localhost
  gather_facts: false
  collections:
    - nutanix.ncp
  module_defaults:
    group/nutanix.ncp.ntnx:
      nutanix_host: <host_ip>
      nutanix_username: <user>
      nutanix_password: <pass>
      validate_certs: false

  tasks:
        
    - name: List floating_ips using ascending ip sorting and floating_ip filter
      ntnx_floating_ips_info:
        filter: "floating_ip==10."
        kind: floating_ip
        sort_order: "ASCENDING"
        sort_attribute: "floating_ip"
      register: result
      ignore_errors: True

    - name: List floating_ips using length and offset
      ntnx_floating_ips_info:
        length: 3
        offset: 0
      register: result
      ignore_errors: True
