---
- name: PBR_Info playbook
  hosts: localhost
  gather_facts: false
  module_defaults:
    group/nutanix.ncp.ntnx:
      nutanix_host: <pc_ip>
      nutanix_username: <user>
      nutanix_password: <pass>
      validate_certs: false

  tasks:
    - name: List pbrs using length and offset
      nutanix.ncp.ntnx_pbrs_info:
        length: 1
        offset: 0
      register: result
      ignore_errors: true

    - name: List pbrs using ascending priority sorting
      nutanix.ncp.ntnx_pbrs_info:
        sort_order: "ASCENDING"
        sort_attribute: "priority"
      register: result
      ignore_errors: true
