########## Permissions Info Module Examples ################################
- name: PC permissions
  hosts: localhost
  gather_facts: false
  module_defaults:
    group/nutanix.ncp.ntnx:
      nutanix_host: "<pc-ip>"
      nutanix_username: "<username>"
      nutanix_password: "<password>"
      validate_certs: false

  tasks:
    - name: Get all permissions
      nutanix.ncp.ntnx_permissions_info:
      register: op1

    - name: Get permissions using filter
      nutanix.ncp.ntnx_permissions_info:
        filter:
          name: <permission_name>
      register: op2

    - name: Get permission using uuid
      nutanix.ncp.ntnx_permissions_info:
        permission_uuid: <permission_uuid>
      register: op3

    - name: Output
      ansible.builtin.debug:
        msg: "{{ op3 }}"
