- name: Roles crud playbook. Here we will create, update, read and delete the role.
  hosts: localhost
  gather_facts: false
  collections:
    - nutanix.ncp
  module_defaults:
    group/nutanix.ncp.ntnx:
      nutanix_host: <pc_ip>
      nutanix_username: <user>
      nutanix_password: <pass>
      validate_certs: false
  tasks:
    - name: get some permissions for adding in roles
      ntnx_permissions_info:
      register: permissions

    - name: Create a role with 2 permissions. Here we will be using name or uuid for referenceing permissions
      ntnx_roles:
        state: present
        name: test-ansible-role-1
        desc:
        permissions:
          - name: "{{ permissions.response.entities[0].status.name }}"
          - uuid: "{{ permissions.response.entities[1].metadata.uuid }}"
        wait: true
      register: role1

    - name: Update role
      ntnx_roles:
        state: present
        role_uuid: "{{ role1.role_uuid }}"
        name: test-ansible-role-1
        permissions:
          - name: "{{ permissions.response.entities[2].status.name }}"
        wait: true
      register: updated_role1

    - name: Read the updated role
      ntnx_roles_info:
        role_uuid: "{{ updated_role1.role_uuid }}"
      register: role1_info

    - name: Print the role details
      debug:
        msg: "{{role1_info}}"

    - name: Delete the role.
      ntnx_roles:
        state: absent
        role_uuid: "{{ updated_role1.role_uuid }}"
        wait: true
      register: op
