---
- name: Subnet_Info playbook
  hosts: localhost
  gather_facts: false
  collections:
    - nutanix.ncp
  module_defaults:
    group/nutanix.ncp.ntnx:
      nutanix_host: <host_ip>
      nutanix_username: <user>
      nutanix_password: <pass>
      validate_certs: false

  tasks:        
    - name: List subnets using subnet_type filter criteria
      ntnx_subnets_info:
        filter: "subnet_type==VLAN"
        kind: subnet
      register: result
      ignore_errors: True
    
    - name: List subnets using length, offset and vlan_id ascending sorting
      ntnx_subnets_info:
        length: 1
        offset: 2
        sort_order: "ASCENDING"
        sort_attribute: "vlan_id"
      check_mode: true
      register: result
      ignore_errors: True
