---
- name: Start overlay subnet task
  ansible.builtin.debug:
    msg: Create {{ item.name }} overlay subnet

- name: Create overlay subnet
  nutanix.ncp.ntnx_subnets:
    state: present
    name: "{{ item.name }}"
    overlay_subnet:
      vpc:
        name: "{{ item.vpc_name }}"
      ipam:
        network_ip: "{{ item.nip }}"
        network_prefix: "{{ item.prefix }}"
        gateway_ip: "{{ item.gip }}"
        ip_pools:
          - start_ip: "{{ item.sip }}"
            end_ip: "{{ item.eip }}"
        dhcp:
          dns_servers: "{{ item.dns_servers }}"
          domain_name: "{{ item.domain_name }}"
          domain_search: "{{ item.domain_search }}"
  register: overlay_subnet_result
- name: Print overlay name and uuid
  ansible.builtin.debug:
    msg:
      - "name: {{ overlay_subnet_result.response.status.name }}"
      - "uuid: {{ overlay_subnet_result.subnet_uuid }}"
