---
- name: Create stretched vlan
  hosts: localhost
  gather_facts: false
  collections:
    - nutanix.ncp
  module_defaults:
    group/nutanix.ncp.ntnx:
      nutanix_host: <ndb-era-ip>
      nutanix_username: <username>
      nutanix_password: <password>
      validate_certs: false

  tasks:
        
    - name: Create stretched vlan
      ntnx_ndb_stretched_vlans:
        name: "{{st_vlan.name}}"
        desc: "{{st_vlan.desc}}"
        vlans:
          - "<vlan_uuid_1>"
          - "<vlan_uuid_2>"
      register: output
    
    - debug:
        msg: "{{output}}"
