---
# Summary:
# This playbook demonstrates how to use proxy configuration with Nutanix v4 API modules.
# Proxy settings can be configured via:
#   1. Module parameters (highest priority)
#   2. Environment variables (fallback)
#
# Supported proxy parameters:
#   - https_proxy / HTTPS_PROXY - HTTPS proxy URL
#   - http_proxy / HTTP_PROXY - HTTP proxy URL
#   - all_proxy / ALL_PROXY - Fallback proxy URL
#   - no_proxy / NO_PROXY - Comma-separated list of hosts to bypass proxy
#   - proxy_username / PROXY_USERNAME - Proxy authentication username
#   - proxy_password / PROXY_PASSWORD - Proxy authentication password
#
# Proxy URL format:
#   - Without auth: http://proxy.example.com:3128
#   - With embedded auth: http://username:password@proxy.example.com:3128

- name: Proxy configuration examples
  hosts: localhost
  gather_facts: false

  # Option 1: Configure proxy via module_defaults (applies to all modules)
  module_defaults:
    group/nutanix.ncp.ntnx:
      nutanix_host: <pc_ip>
      nutanix_username: <user>
      nutanix_password: <pass>
      validate_certs: false
      # Proxy URL with embedded credentials
      https_proxy: "http://proxyuser:proxypass@proxy.example.com:3128"
      # Or use separate credentials
      # https_proxy: "http://proxy.example.com:3128"
      # proxy_username: "proxyuser"
      # proxy_password: "proxypass"

  tasks:
    # =========================================================================
    # Example 1: List VMs through proxy (VMM SDK)
    # =========================================================================
    - name: List VMs using proxy configured in module_defaults
      nutanix.ncp.ntnx_vms_info_v2:
      register: vms_result

    - name: Display VMs count
      ansible.builtin.debug:
        msg: "Retrieved {{ vms_result.response | length }} VMs through proxy"

    # =========================================================================
    # Example 2: Override proxy for specific module
    # =========================================================================
    - name: List clusters with different proxy
      nutanix.ncp.ntnx_clusters_info_v2:
        https_proxy: "http://altuser:altpass@alt-proxy.example.com:8080"
      register: clusters_result

    - name: Display clusters count
      ansible.builtin.debug:
        msg: "Retrieved {{ clusters_result.response | length }} clusters"

    # =========================================================================
    # Example 3: Bypass proxy for specific host using no_proxy
    # =========================================================================
    - name: List categories bypassing proxy for pc ip
      nutanix.ncp.ntnx_categories_info_v2:
        no_proxy: "{{ pc_ip }}"
      register: categories_result

    - name: Display categories count
      ansible.builtin.debug:
        msg: "Retrieved {{ categories_result.response | length }} categories"

    # =========================================================================
    # Example 4: Use separate proxy credentials
    # =========================================================================
    - name: List VPCs with separate proxy credentials
      nutanix.ncp.ntnx_vpcs_info_v2:
        https_proxy: "http://proxy.example.com:3128"
        proxy_username: "myproxyuser"
        proxy_password: "myproxypassword"
      register: vpcs_result

    - name: Display VPCs count
      ansible.builtin.debug:
        msg: "Retrieved {{ vpcs_result.response | length }} VPCs"

    # =========================================================================
    # Example 5: Disable proxy for specific module
    # =========================================================================
    - name: List users without proxy (direct connection)
      nutanix.ncp.ntnx_users_info_v2:
        https_proxy: ""
      register: users_result

    - name: Display users count
      ansible.builtin.debug:
        msg: "Retrieved {{ users_result.response | length }} users"

- name: Proxy via environment variables example
  hosts: localhost
  gather_facts: false

  # Option 2: Configure proxy via environment variables
  # Environment variables are used as fallback when module params are not set
  environment:
    HTTPS_PROXY: "http://proxyuser:proxypass@proxy.example.com:3128"
    HTTP_PROXY: "http://proxyuser:proxypass@proxy.example.com:3128"
    # Or use separate credentials
    # PROXY_USERNAME: "proxyuser"
    # PROXY_PASSWORD: "proxypass"

  module_defaults:
    group/nutanix.ncp.ntnx:
      nutanix_host: <pc_ip>
      nutanix_username: <user>
      nutanix_password: <pass>
      validate_certs: false
      # Note: https_proxy is NOT set here, so env vars will be used

  tasks:
    - name: List VMs using proxy from environment variables
      nutanix.ncp.ntnx_vms_info_v2:
      register: vms_result

    - name: Display VMs count
      ansible.builtin.debug:
        msg: "Retrieved {{ vms_result.response | length }} VMs via env var proxy"

- name: All SDKs proxy validation example
  hosts: localhost
  gather_facts: false
  module_defaults:
    group/nutanix.ncp.ntnx:
      nutanix_host: <pc_ip>
      nutanix_username: <user>
      nutanix_password: <pass>
      validate_certs: false
      https_proxy: "http://proxyuser:proxypass@proxy.example.com:3128"

  tasks:
    # =========================================================================
    # Test all 13 v4 API SDKs through proxy
    # =========================================================================

    # SDK 1: ntnx_vmm_py_client
    - name: "[VMM SDK] List VMs"
      nutanix.ncp.ntnx_vms_info_v2:
      register: vmm_result
      ignore_errors: true

    # SDK 2: ntnx_networking_py_client
    - name: "[Network SDK] List VPCs"
      nutanix.ncp.ntnx_vpcs_info_v2:
      register: network_result
      ignore_errors: true

    # SDK 3: ntnx_iam_py_client
    - name: "[IAM SDK] List Users"
      nutanix.ncp.ntnx_users_info_v2:
      register: iam_result
      ignore_errors: true

    # SDK 4: ntnx_clustermgmt_py_client
    - name: "[ClusterMgmt SDK] List Clusters"
      nutanix.ncp.ntnx_clusters_info_v2:
      register: clustermgmt_result
      ignore_errors: true

    # SDK 5: ntnx_prism_py_client
    - name: "[Prism SDK] List Categories"
      nutanix.ncp.ntnx_categories_info_v2:
      register: prism_result
      ignore_errors: true

    # SDK 6: ntnx_volumes_py_client
    - name: "[Volumes SDK] List Volume Groups"
      nutanix.ncp.ntnx_volume_groups_info_v2:
      register: volumes_result
      ignore_errors: true

    # SDK 7: ntnx_dataprotection_py_client
    - name: "[DataProtection SDK] List Recovery Points"
      nutanix.ncp.ntnx_recovery_points_info_v2:
      register: dataprotection_result
      ignore_errors: true

    # SDK 8: ntnx_microseg_py_client
    - name: "[Flow/Microseg SDK] List Address Groups"
      nutanix.ncp.ntnx_address_groups_info_v2:
      register: flow_result
      ignore_errors: true

    # SDK 9: ntnx_lifecycle_py_client
    - name: "[LCM SDK] Get LCM Status"
      nutanix.ncp.ntnx_lcm_status_info_v2:
      register: lcm_result
      ignore_errors: true

    # SDK 10: ntnx_datapolicies_py_client
    - name: "[DataPolicies SDK] List Protection Policies"
      nutanix.ncp.ntnx_protection_policies_info_v2:
      register: datapolicies_result
      ignore_errors: true

    # SDK 11: ntnx_objects_py_client
    - name: "[Objects SDK] List Object Stores"
      nutanix.ncp.ntnx_object_stores_info_v2:
      register: objects_result
      ignore_errors: true

    # SDK 12: ntnx_licensing_py_client
    - name: "[Licensing SDK] Get EULA Info"
      nutanix.ncp.ntnx_eula_info_v2:
      register: licensing_result
      ignore_errors: true

    # SDK 13: ntnx_security_py_client
    - name: "[Security SDK] List STIGs"
      nutanix.ncp.ntnx_stigs_info_v2:
      register: security_result
      ignore_errors: true

    - name: Display Results Summary
      ansible.builtin.debug:
        msg:
          - "Proxy Validation Results:"
          - "  VMM SDK:            {{ 'OK' if vmm_result is not failed else 'FAILED' }}"
          - "  Network SDK:        {{ 'OK' if network_result is not failed else 'FAILED' }}"
          - "  IAM SDK:            {{ 'OK' if iam_result is not failed else 'FAILED' }}"
          - "  ClusterMgmt SDK:    {{ 'OK' if clustermgmt_result is not failed else 'FAILED' }}"
          - "  Prism SDK:          {{ 'OK' if prism_result is not failed else 'FAILED' }}"
          - "  Volumes SDK:        {{ 'OK' if volumes_result is not failed else 'FAILED' }}"
          - "  DataProtection SDK: {{ 'OK' if dataprotection_result is not failed else 'FAILED' }}"
          - "  Flow SDK:           {{ 'OK' if flow_result is not failed else 'FAILED' }}"
          - "  LCM SDK:            {{ 'OK' if lcm_result is not failed else 'FAILED' }}"
          - "  DataPolicies SDK:   {{ 'OK' if datapolicies_result is not failed else 'FAILED' }}"
          - "  Objects SDK:        {{ 'OK' if objects_result is not failed else 'FAILED' }}"
          - "  Licensing SDK:      {{ 'OK' if licensing_result is not failed else 'FAILED' }}"
          - "  Security SDK:       {{ 'OK' if security_result is not failed else 'FAILED' }}"
