plugin: nutanix.ncp.ntnx_prism_vm_inventory
nutanix_hostname: <pc_ip>
nutanix_username: <username>
nutanix_password: <password>
validate_certs: false
data: {"offset": 0, "length": 1000}
groups:
  group_1: "'<name_prefix>' in name"
  group_2: "'<vm_name>'==name"
keyed_groups:
  - prefix: "host"
    separator: ':'
    key: "ansible_host"