---
# Summary:
# This playbook will do:
# 1. Get End of User License Agreement info before acceptance
# 2. Accept End of User License Agreement

- name: Licensing EULA v2 playbook
  hosts: localhost
  gather_facts: false
  module_defaults:
    group/nutanix.ncp.ntnx:
      nutanix_host: <pc_ip>
      nutanix_username: <user>
      nutanix_password: <pass>
      validate_certs: false
  tasks:
    - name: Setting Variables
      ansible.builtin.set_fact:
        user_name: "user_name"
        login_id: "login_id"
        job_title: "job_title"
        company_name: "company_name"

    - name: Get End of User License Agreement info
      nutanix.ncp.ntnx_eula_info_v2:
      register: result
      ignore_errors: true

    - name: Accept End of User License Agreement
      nutanix.ncp.ntnx_eula_accept_v2:
        user_name: "{{ user_name }}"
        login_id: "{{ login_id }}"
        job_title: "{{ job_title }}"
        company_name: "{{ company_name }}"
      register: result
      ignore_errors: true
