#!/usr/bin/python
# -*- coding: utf-8 -*-

# Copyright: (c) 2026, Nutanix
# GNU General Public License v3.0+ (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)

from __future__ import absolute_import, division, print_function

__metaclass__ = type

DOCUMENTATION = r"""
---
module: ntnx_vpn_appliances_by_vpn_connection_id_v2
short_description: Download third-party VPN appliance configuration for a Nutanix VPN connection
version_added: 2.5.0
description:
  - This module downloads the third-party VPN appliance (vendor) configuration for a given Nutanix VPN connection.
  - The Nutanix VPN service can generate ready-to-apply configuration text for supported on-premise
    third-party VPN gateways (for example Palo Alto, Checkpoint, Juniper). Given a VPN connection
    C(vpn_connection_ext_id) and a specific appliance C(ext_id) (returned by the sibling info module),
    this module retrieves the exact configuration payload the user should apply on their on-premise device.
  - This entity is read-only from the Prism Central v4 API surface. There is no create, update, or delete
    operation for a VPN appliance vendor configuration - it is generated by the platform based on the
    VPN connection parameters. State C(present) is therefore the only supported state and running this
    module never mutates cluster state.
  - This module uses PC v4 APIs based SDKs.
notes:
    - >-
      This module requires the following Nutanix IAM roles to be assigned to the user performing the operation.
      The required roles depend on the operation being performed.
    - >-
      B(Download third-party VPN appliance configuration) -
      Required Roles: Consumer, Developer, Network Infra Admin, Operator, Prism Admin, Prism Viewer,
      Project Admin, Super Admin, VPC Admin
    - "Ref: U(https://developers.nutanix.com/api-reference?namespace=networking)"
options:
  state:
    description:
      - Only C(present) is supported. This module never modifies cluster state, it only downloads the
        vendor configuration for a VPN appliance.
    type: str
    required: false
    choices:
      - present
    default: present
  vpn_connection_ext_id:
    description:
      - External ID of the VPN connection the appliance configuration belongs to.
    type: str
    required: true
  ext_id:
    description:
      - External ID of the third-party VPN appliance whose configuration should be downloaded.
      - This value is one of the appliance C(ext_id) values returned by
        M(nutanix.ncp.ntnx_vpn_appliances_by_vpn_connection_ids_info_v2).
    type: str
    required: true
extends_documentation_fragment:
  - nutanix.ncp.ntnx_credentials
  - nutanix.ncp.ntnx_operations_v2
  - nutanix.ncp.ntnx_logger
  - nutanix.ncp.ntnx_proxy_v2
author:
  - George Ghawali (@george-ghawali)
  - Abhinav Bansal (@abhinavbansal29)
"""

EXAMPLES = r"""
- name: Download third-party VPN appliance configuration
  nutanix.ncp.ntnx_vpn_appliances_by_vpn_connection_id_v2:
    nutanix_host: "{{ ip }}"
    nutanix_username: "{{ username }}"
    nutanix_password: "{{ password }}"
    validate_certs: false
    state: present
    vpn_connection_ext_id: "2e40ff57-20aa-4d2b-b179-298db969c20d"
    ext_id: "9f4b3d1c-6a15-4c8b-9d12-6b6b9f13a1b2"
  register: result
  ignore_errors: true
"""

RETURN = r"""
response:
  description:
    - The vendor configuration payload for the third-party VPN appliance.
    - The API returns the configuration as plain text (a set of vendor-specific commands / directives)
      that the user should apply on their on-premise VPN gateway.
  returned: always
  type: str
  sample: "<need_to_add_sample>"

vpn_connection_ext_id:
  description:
    - External ID of the VPN connection the appliance configuration was fetched for.
  returned: always
  type: str
  sample: "2e40ff57-20aa-4d2b-b179-298db969c20d"

ext_id:
  description:
    - External ID of the third-party VPN appliance whose configuration was downloaded.
  returned: always
  type: str
  sample: "9f4b3d1c-6a15-4c8b-9d12-6b6b9f13a1b2"

task_ext_id:
  description:
    - Task external ID.
    - Always C(null) for this module because downloading vendor configuration is a synchronous read-only
      operation and does not create a task.
  returned: always
  type: str
  sample: null

changed:
  description: This indicates whether the task resulted in any changes. Always false for this module.
  returned: always
  type: bool
  sample: false

skipped:
  description: This indicates whether the task was skipped (only set in check mode).
  returned: when applicable
  type: bool
  sample: true

error:
  description: This indicates the error message if any error occurred
  returned: When an error occurs
  type: str

failed:
  description: This indicates whether the task failed
  returned: always
  type: bool
  sample: false

msg:
  description: Status or error message.
  returned: When there is an error or the module is running in check mode
  type: str
  sample: "Api Exception raised while fetching third-party VPN appliance configuration for vpn_connection_ext_id=... and ext_id=..."
"""

import traceback  # noqa: E402
import warnings  # noqa: E402

from ansible.module_utils.basic import missing_required_lib  # noqa: E402

from ..module_utils.utils import remove_param_with_none_value  # noqa: E402
from ..module_utils.v4.base_module_v4 import BaseModuleV4  # noqa: E402
from ..module_utils.v4.network.api_client import (  # noqa: E402
    get_vpn_connections_api_instance,
)
from ..module_utils.v4.network.helpers import get_vpn_appliance_config  # noqa: E402
from ..module_utils.v4.utils import validate_required_params  # noqa: E402

SDK_IMP_ERROR = None
try:
    import ntnx_networking_py_client as networking_sdk  # noqa: E402
except ImportError:

    from ..module_utils.v4.sdk_mock import mock_sdk as networking_sdk  # noqa: E402

    SDK_IMP_ERROR = traceback.format_exc()

# Reference the SDK module explicitly so static analysers see it as used.
# The import above exists so ansible-doc can parse this file even when the
# real SDK is not installed (mock_sdk fallback); the reference to
# ``__name__`` here is a no-op at runtime.
_SDK_MODULE_NAME = getattr(networking_sdk, "__name__", "ntnx_networking_py_client")

warnings.filterwarnings("ignore", message="Unverified HTTPS request is being made")


def get_module_spec():
    module_args = dict(
        state=dict(type="str", choices=["present"], default="present"),
        vpn_connection_ext_id=dict(type="str", required=True),
        ext_id=dict(type="str", required=True),
    )
    return module_args


def download_vpn_appliance_config(module, api_instance, result):
    validate_required_params(module, ["vpn_connection_ext_id", "ext_id"])
    vpn_connection_ext_id = module.params.get("vpn_connection_ext_id")
    ext_id = module.params.get("ext_id")
    result["vpn_connection_ext_id"] = vpn_connection_ext_id
    result["ext_id"] = ext_id

    if module.check_mode:
        result["skipped"] = True
        result["msg"] = (
            "Third-party VPN appliance configuration will be downloaded for "
            "vpn_connection_ext_id:{0} and ext_id:{1}.".format(
                vpn_connection_ext_id, ext_id
            )
        )
        return

    resp = get_vpn_appliance_config(
        module=module,
        api_instance=api_instance,
        vpn_connection_ext_id=vpn_connection_ext_id,
        ext_id=ext_id,
    )
    if resp is None:
        module.fail_json(
            msg=(
                "Empty response while fetching third-party VPN appliance "
                "configuration for vpn_connection_ext_id={0} and ext_id={1}".format(
                    vpn_connection_ext_id, ext_id
                )
            ),
            **result,
        )
    result["response"] = resp


def run_module():
    module = BaseModuleV4(
        argument_spec=get_module_spec(),
        supports_check_mode=True,
    )
    if SDK_IMP_ERROR:
        module.fail_json(
            msg=missing_required_lib("ntnx_networking_py_client"),
            exception=SDK_IMP_ERROR,
        )

    remove_param_with_none_value(module.params)
    result = {
        "changed": False,
        "response": None,
        "failed": False,
        "vpn_connection_ext_id": None,
        "ext_id": None,
        "task_ext_id": None,
    }
    api_instance = get_vpn_connections_api_instance(module)
    download_vpn_appliance_config(module, api_instance, result)
    module.exit_json(**result)


def main():
    run_module()


if __name__ == "__main__":
    main()
