#!/usr/bin/python
# -*- coding: utf-8 -*-

# Copyright: (c) 2026, Nutanix
# GNU General Public License v3.0+ (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)

from __future__ import absolute_import, division, print_function

__metaclass__ = type

DOCUMENTATION = r"""
---
module: ntnx_validation_errors_by_recovery_plan_job_ids_info_v2
short_description: Fetch validation errors of a Recovery Plan Job in Nutanix Prism Central
version_added: 2.5.0
description:
  - This module allows you to fetch information about ValidationErrorsByRecoveryPlanJobId in Nutanix Prism Central.
  - List the validation errors and warnings generated by a Recovery Plan Job during its pre-execution checks.
  - The parent recovery plan job C(recovery_plan_job_ext_id) is required.
  - Supports optional pagination and OData filtering / ordering.
  - This module uses PC v4 APIs based SDKs.
options:
  recovery_plan_job_ext_id:
    description:
      - The external identifier of the parent Recovery Plan Job whose validation errors are to be fetched.
    type: str
    required: true
extends_documentation_fragment:
  - nutanix.ncp.ntnx_credentials
  - nutanix.ncp.ntnx_info_v2
  - nutanix.ncp.ntnx_logger
  - nutanix.ncp.ntnx_proxy_v2
author:
  - George Ghawali (@george-ghawali)
"""
EXAMPLES = r"""
- name: List all validation errors for a recovery plan job
  nutanix.ncp.ntnx_validation_errors_by_recovery_plan_job_ids_info_v2:
    recovery_plan_job_ext_id: "2e40ff57-20aa-4d2b-b179-298db969c20d"
  register: result
  ignore_errors: true

- name: List validation errors for a recovery plan job with a limit
  nutanix.ncp.ntnx_validation_errors_by_recovery_plan_job_ids_info_v2:
    recovery_plan_job_ext_id: "2e40ff57-20aa-4d2b-b179-298db969c20d"
    limit: 5
  register: result
  ignore_errors: true

- name: List validation errors for a recovery plan job ordered by extId (descending)
  nutanix.ncp.ntnx_validation_errors_by_recovery_plan_job_ids_info_v2:
    recovery_plan_job_ext_id: "2e40ff57-20aa-4d2b-b179-298db969c20d"
    orderby: "extId desc"
  register: result
  ignore_errors: true

- name: Fetch a single validation error by its external ID using an OData filter
  nutanix.ncp.ntnx_validation_errors_by_recovery_plan_job_ids_info_v2:
    recovery_plan_job_ext_id: "2e40ff57-20aa-4d2b-b179-298db969c20d"
    filter: "extId eq 'e8f4a3a1-1b2f-4a1b-9c4a-2c19e7a954a3'"
  register: result
  ignore_errors: true
"""
RETURN = r"""
response:
  description:
    - The response from the Nutanix PC ValidationErrorsByRecoveryPlanJobId info v4 API.
    - A list of validation errors / warnings for the given Recovery Plan Job.
    - If no validation errors exist, an empty list is returned.
  returned: always
  type: dict
  sample:
    [
      {
        "affected_entities": [
          {
            "ext_id": "2e572ceb-d955-4ed7-956f-1c90acf5b5ad"
          }
        ],
        "error_code": "DP-303044",
        "error_group": "NETWORK",
        "ext_id": "e8f4a3a1-1b2f-4a1b-9c4a-2c19e7a954a3",
        "links": null,
        "message": "Network mapping will not happen post failover as it is not defined for the Recovery Plan.",
        "root_cause_analysis": {
          "cause": "Network mapping is not configured for this Recovery Plan.",
          "impacts": [
            "Failover will proceed but network mapping will not be applied."
          ],
          "resolutions": [
            "Configure network mapping for the Recovery Plan on the Recovery Availability Zone."
          ]
        },
        "severity": "WARNING",
        "tenant_id": null
      }
    ]

changed:
  description: This indicates whether the task resulted in any changes
  returned: always
  type: bool
  sample: false

msg:
  description: This indicates the message if any message occurred
  returned: When there is an error
  type: str
  sample: "Api Exception raised while fetching recovery plan job validation errors info"

error:
  description: This field typically holds information about if the task have errors that occurred during the task execution
  type: str
  returned: when an error occurs
  sample: null

failed:
  description: This field typically holds information about if the task have failed
  returned: always
  type: bool
  sample: false

total_available_results:
  description: The total number of available validation errors for the given Recovery Plan Job.
  type: int
  returned: always
  sample: 3
"""

import warnings  # noqa: E402

from ..module_utils.utils import remove_param_with_none_value  # noqa: E402
from ..module_utils.v4.base_info_module import BaseInfoModule  # noqa: E402
from ..module_utils.v4.data_protection.api_client import (  # noqa: E402
    get_recovery_plan_jobs_api_instance,
)
from ..module_utils.v4.data_protection.helpers import (  # noqa: E402
    list_recovery_plan_job_validation_errors,
)
from ..module_utils.v4.spec_generator import SpecGenerator  # noqa: E402
from ..module_utils.v4.utils import strip_internal_attributes  # noqa: E402

# Suppress the InsecureRequestWarning
warnings.filterwarnings("ignore", message="Unverified HTTPS request is being made")


def get_module_spec():

    module_args = dict(
        recovery_plan_job_ext_id=dict(type="str", required=True),
    )

    return module_args


def list_validation_errors_by_recovery_plan_job(module, api_instance, result):
    recovery_plan_job_ext_id = module.params.get("recovery_plan_job_ext_id")

    sg = SpecGenerator(module)
    kwargs, err = sg.get_info_spec(attr=module.params)
    if err:
        result["error"] = err
        module.fail_json(
            msg="Failed generating recovery plan job validation errors info spec",
            **result,
        )

    # The SDK method does not support `_select`; drop it if present.
    kwargs.pop("_select", None)

    resp = list_recovery_plan_job_validation_errors(
        module=module,
        api_instance=api_instance,
        recovery_plan_job_ext_id=recovery_plan_job_ext_id,
        **kwargs,
    )

    result["recovery_plan_job_ext_id"] = recovery_plan_job_ext_id

    total_available_results = getattr(
        getattr(resp, "metadata", None), "total_available_results", None
    )
    if total_available_results is not None:
        result["total_available_results"] = total_available_results

    data = strip_internal_attributes(resp.to_dict()).get("data")
    if not data:
        data = []
    result["response"] = data


def run_module():
    module = BaseInfoModule(
        argument_spec=get_module_spec(),
        supports_check_mode=False,
    )
    remove_param_with_none_value(module.params)
    result = {"changed": False, "error": None, "response": None}
    api_instance = get_recovery_plan_jobs_api_instance(module)
    list_validation_errors_by_recovery_plan_job(module, api_instance, result)
    module.exit_json(**result)


def main():
    run_module()


if __name__ == "__main__":
    main()
