#!/usr/bin/python
# -*- coding: utf-8 -*-

# Copyright: (c) 2026, Nutanix
# GNU General Public License v3.0+ (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)

from __future__ import absolute_import, division, print_function

__metaclass__ = type

DOCUMENTATION = r"""
---
module: ntnx_reports_info_v2
short_description: Fetch report info in Nutanix Prism Central
version_added: 2.7.0
description:
  - This module allows you to fetch information about Report in Nutanix Prism Central.
  - If C(ext_id) is provided, fetch details of the specific Report.
  - If C(ext_id) is not provided, list multiple Report optionally filtered / paginated.
  - This module uses PC v4 APIs based SDKs.
notes:
    - >-
      This module requires the following Nutanix IAM roles to be assigned to the user performing the operation.
    - >-
      B(Get Report by ext_id) -
      Required Roles: NCM Admin, NCM Viewer, Intelligent Ops Admin,
      Operations Management Admin, Operations Management Viewer,
      Prism Admin, Prism Viewer, Super Admin, Internal Super Admin.
    - >-
      B(List Reports) -
      Required Roles: NCM Admin, NCM Viewer, Intelligent Ops Admin,
      Operations Management Admin, Operations Management Viewer,
      Prism Admin, Prism Viewer, Super Admin, Internal Super Admin.
    - "Ref: U(https://developers.nutanix.com/api-reference?namespace=opsmgmt)"
options:
  ext_id:
    description:
      - The external ID of the report.
      - When provided, the module returns a single report; otherwise the module
        returns a paginated list of reports.
    type: str
extends_documentation_fragment:
  - nutanix.ncp.ntnx_credentials
  - nutanix.ncp.ntnx_info_v2
  - nutanix.ncp.ntnx_logger
  - nutanix.ncp.ntnx_proxy_v2
author:
  - Abhinav Bansal (@abhinavbansal29)
  - George Ghawali (@george-ghawali)
"""

EXAMPLES = r"""
- name: Fetch a specific report using external ID
  nutanix.ncp.ntnx_reports_info_v2:
    nutanix_host: "{{ ip }}"
    nutanix_username: "{{ username }}"
    nutanix_password: "{{ password }}"
    validate_certs: false
    ext_id: "77777777-8888-9999-aaaa-bbbbbbbbbbbb"
  register: result
  ignore_errors: true

- name: List all reports
  nutanix.ncp.ntnx_reports_info_v2:
    nutanix_host: "{{ ip }}"
    nutanix_username: "{{ username }}"
    nutanix_password: "{{ password }}"
    validate_certs: false
  register: result
  ignore_errors: true

- name: List reports with filter
  nutanix.ncp.ntnx_reports_info_v2:
    nutanix_host: "{{ ip }}"
    nutanix_username: "{{ username }}"
    nutanix_password: "{{ password }}"
    validate_certs: false
    filter: "name eq 'monthly_vm_report_full'"
  register: result
  ignore_errors: true

- name: List reports with limit
  nutanix.ncp.ntnx_reports_info_v2:
    nutanix_host: "{{ ip }}"
    nutanix_username: "{{ username }}"
    nutanix_password: "{{ password }}"
    validate_certs: false
    limit: 1
  register: result
  ignore_errors: true
"""

RETURN = r"""
response:
  description:
    - The response from the Nutanix PC Report info v4 API.
    - It can be a single Report if external ID is provided.
    - List of multiple Report if external ID is not provided with optional filter or limit.
  returned: always
  type: dict
  sample:
    {
      "available_formats": ["PDF"],
      "config_ext_id": "aaaaaaaa-1111-2222-3333-444444444444",
      "creation_time": "2026-02-01T00:00:00+00:00",
      "description": "Monthly VM efficiency report generated by Ansible",
      "end_time": "2026-01-31T23:59:59+00:00",
      "entity_selection": null,
      "ext_id": "77777777-8888-9999-aaaa-bbbbbbbbbbbb",
      "is_persistent": true,
      "links": null,
      "name": "monthly_vm_report_full",
      "override_supported_formats": ["PDF"],
      "owner_ext_id": "00000000-0000-0000-0000-000000000001",
      "recipient_formats": ["PDF"],
      "recipients": [
          {
              "email_address": "ops-lead@example.com",
              "recipient_name": "Ops Lead"
          }
      ],
      "start_time": "2026-01-01T00:00:00+00:00",
      "tenant_id": null,
      "timezone": "UTC"
    }

changed:
  description: This indicates whether the task resulted in any changes
  returned: always
  type: bool
  sample: false

msg:
  description: This indicates the message if any message occurred
  returned: When there is an error
  type: str
  sample: "Api Exception raised while fetching reports info"

error:
  description:
    - This field typically holds information about if the task have errors that occurred during the task execution.
  type: str
  returned: When an error occurs

failed:
  description: This field typically holds information about if the task have failed
  returned: always
  type: bool
  sample: false

ext_id:
  description: External ID of the report
  type: str
  returned: When external ID is provided
  sample: "77777777-8888-9999-aaaa-bbbbbbbbbbbb"

total_available_results:
  description: The total number of available reports in PC.
  type: int
  returned: When all reports are fetched
  sample: 5
"""

import warnings  # noqa: E402

from ..module_utils.utils import remove_param_with_none_value  # noqa: E402
from ..module_utils.v4.base_info_module import BaseInfoModule  # noqa: E402
from ..module_utils.v4.opsmgmt.api_client import get_reports_api_instance  # noqa: E402
from ..module_utils.v4.opsmgmt.helpers import get_report  # noqa: E402
from ..module_utils.v4.spec_generator import SpecGenerator  # noqa: E402
from ..module_utils.v4.utils import (  # noqa: E402
    raise_api_exception,
    strip_internal_attributes,
)

# Suppress the InsecureRequestWarning
warnings.filterwarnings("ignore", message="Unverified HTTPS request is being made")


def get_module_spec():

    module_args = dict(
        ext_id=dict(type="str"),
    )

    return module_args


def get_report_using_ext_id(module, api_instance, result):
    ext_id = module.params.get("ext_id")
    resp = get_report(module, api_instance, ext_id)
    result["ext_id"] = ext_id
    result["response"] = strip_internal_attributes(resp.to_dict())


def get_reports(module, api_instance, result):
    sg = SpecGenerator(module)
    kwargs, err = sg.get_info_spec(attr=module.params)
    if err:
        result["error"] = err
        module.fail_json(msg="Failed generating reports info spec", **result)

    try:
        resp = api_instance.list_reports(**kwargs)
    except Exception as e:
        raise_api_exception(
            module=module,
            exception=e,
            msg="Api Exception raised while fetching reports info",
        )

    total_available_results = resp.metadata.total_available_results
    result["total_available_results"] = total_available_results
    resp = strip_internal_attributes(resp.to_dict()).get("data")
    if not resp:
        resp = []
    result["response"] = resp


def run_module():
    module = BaseInfoModule(
        argument_spec=get_module_spec(),
        supports_check_mode=False,
        mutually_exclusive=[
            ("ext_id", "filter"),
        ],
    )
    remove_param_with_none_value(module.params)
    result = {"changed": False, "response": None, "failed": False}
    api_instance = get_reports_api_instance(module)
    if module.params.get("ext_id"):
        get_report_using_ext_id(module, api_instance, result)
    else:
        get_reports(module, api_instance, result)
    module.exit_json(**result)


def main():
    run_module()


if __name__ == "__main__":
    main()
