#!/usr/bin/python
# -*- coding: utf-8 -*-

# Copyright: (c) 2026, Nutanix
# GNU General Public License v3.0+ (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)

from __future__ import absolute_import, division, print_function

__metaclass__ = type

DOCUMENTATION = r"""
---
module: ntnx_files_recommendation_v2
short_description: Delete a file server recommendation in Nutanix Prism Central
version_added: 2.7.0
description:
  - This module allows you to delete (dismiss) a file server recommendation in Nutanix Prism Central.
  - Recommendations are generated by the file server and cannot be created or updated,
    hence only the delete operation (C(state=absent)) is supported by this module.
  - Use M(nutanix.ncp.ntnx_files_recommendations_info_v2) to fetch or list recommendations.
  - This module uses PC v4 APIs based SDKs.
notes:
  - Recommendations are system generated for a file server, so this module supports
    only the delete operation.
  - "Ref: U(https://developers.nutanix.com/api-reference?namespace=files)"
options:
  state:
    description:
      - If C(state) is set to C(absent) and C(ext_id) is provided then the operation will be
        delete the file server recommendation.
      - C(present) is not supported for this module because recommendations cannot be created or updated.
    type: str
    required: false
    choices:
      - present
      - absent
    default: present
  ext_id:
    description:
      - The external identifier of the recommendation.
      - Required for the delete operation.
    type: str
    required: false
  file_server_ext_id:
    description:
      - The external identifier of the file server that owns the recommendation.
    type: str
    required: true
extends_documentation_fragment:
  - nutanix.ncp.ntnx_credentials
  - nutanix.ncp.ntnx_operations_v2
  - nutanix.ncp.ntnx_logger
  - nutanix.ncp.ntnx_proxy_v2
author:
  - Abhinav Bansal (@abhinavbansal29)
  - George Ghawali (@george-ghawali)
"""

EXAMPLES = r"""
- name: Delete a file server recommendation
  nutanix.ncp.ntnx_files_recommendation_v2:
    nutanix_host: "{{ ip }}"
    nutanix_username: "{{ username }}"
    nutanix_password: "{{ password }}"
    validate_certs: false
    state: absent
    file_server_ext_id: "38dc16f4-90b6-4b1c-8b8c-1f0fdc7b3a2e"
    ext_id: "b1c2d3e4-90b6-4b1c-8b8c-1f0fdc7b3a2e"
  register: result
  ignore_errors: true
"""

RETURN = r"""
response:
  description:
    - Response for deleting the file server recommendation.
  returned: always
  type: dict
  sample:
    {
      "data": {},
      "metadata": {
          "flags": null,
          "links": null,
          "messages": null,
          "total_available_results": null
      }
    }

ext_id:
  description:
    - The external identifier of the recommendation that was deleted.
  returned: always
  type: str
  sample: "b1c2d3e4-90b6-4b1c-8b8c-1f0fdc7b3a2e"

task_ext_id:
  description:
    - The external identifier of the task, when the delete operation is processed asynchronously.
  returned: when the delete operation returns a task
  type: str
  sample: "ZXJnb24=:90458bc7-a12b-4616-ac66-562fdb00c209"

changed:
  description: This indicates whether the task resulted in any changes.
  returned: always
  type: bool
  sample: true

error:
  description: This indicates the error message if any error occurred.
  returned: When an error occurs
  type: str

failed:
  description: This indicates whether the task failed.
  returned: always
  type: bool
  sample: false

msg:
  description: This indicates the message if any message occurred.
  returned: When there is an error or in check mode (in delete operation)
  type: str
  sample: "Recommendation with ext_id:b1c2d3e4-90b6-4b1c-8b8c-1f0fdc7b3a2e will be deleted."
"""

import warnings  # noqa: E402

from ..module_utils.utils import remove_param_with_none_value  # noqa: E402
from ..module_utils.v4.base_module_v4 import BaseModuleV4  # noqa: E402
from ..module_utils.v4.files.api_client import (  # noqa: E402
    get_recommendations_api_instance,
)
from ..module_utils.v4.utils import (  # noqa: E402
    raise_api_exception,
    strip_internal_attributes,
)

# Suppress the InsecureRequestWarning
warnings.filterwarnings("ignore", message="Unverified HTTPS request is being made")


def get_module_spec():

    module_args = dict(
        ext_id=dict(type="str"),
        file_server_ext_id=dict(type="str", required=True),
    )
    return module_args


def delete_recommendation(module, recommendations_api, result):
    file_server_ext_id = module.params.get("file_server_ext_id")
    ext_id = module.params.get("ext_id")
    result["ext_id"] = ext_id

    if module.check_mode:
        result["msg"] = "Recommendation with ext_id:{0} will be deleted.".format(ext_id)
        return

    resp = None
    try:
        resp = recommendations_api.delete_recommendation_by_id(
            fileServerExtId=file_server_ext_id, extId=ext_id
        )
    except Exception as e:
        raise_api_exception(
            module=module,
            exception=e,
            msg="Api Exception raised while deleting recommendation",
        )

    if resp is not None:
        result["response"] = strip_internal_attributes(resp.to_dict())
    result["changed"] = True


def run_module():
    module = BaseModuleV4(
        argument_spec=get_module_spec(),
        supports_check_mode=True,
        required_if=[
            ("state", "absent", ("ext_id",)),
        ],
    )
    remove_param_with_none_value(module.params)
    result = {
        "changed": False,
        "response": None,
        "ext_id": None,
        "task_ext_id": None,
        "failed": False,
    }
    recommendations_api = get_recommendations_api_instance(module)
    state = module.params.get("state")
    if state == "present":
        module.fail_json(
            msg=(
                "Recommendations are generated by the file server and cannot be created "
                "or updated. Only the delete operation (state=absent) is supported by "
                "this module."
            ),
            **result,
        )
    delete_recommendation(module, recommendations_api, result)
    module.exit_json(**result)


def main():
    run_module()


if __name__ == "__main__":
    main()
