---
# Summary:
# This playbook will do:
# 1. Attach VM to Volume Group
# 2. Detach VM from Volume Group

- name: Volume groups vms playbook
  hosts: localhost
  gather_facts: false
  module_defaults:
    group/nutanix.ncp.ntnx:
      nutanix_host: <pc_ip>
      nutanix_username: <user>
      nutanix_password: <pass>
      validate_certs: false
  tasks:
    - name: Setting Variables
      ansible.builtin.set_fact:
        vg1_uuid: "f4b1b3b4-4b1b-4b1b-4b1b-4b1b4b1b4b1b"
        vm1_uuid: "a1b2c3d4-e5f6-7g8h-9i0j-k1l2m3n4o5p6"

    - name: Attach VM1 to VG
      ntnx_volume_groups_vms_v2:
        state: present
        volume_group_ext_id: "{{ vg1_uuid }}"
        ext_id: "{{ vm1_uuid }}"
        index: 1
      register: result

    - name: Detach VM1 from VG
      ntnx_volume_groups_vms_v2:
        state: absent
        volume_group_ext_id: "{{ vg1_uuid }}"
        ext_id: "{{ vm1_uuid }}"
      register: result
